# Image pipline

In [1]:
# flake8: noqa

import numpy as np
import pandas as pd
from PIL import Image

from datapipe.datatable import DataStore
from datapipe.store.filedir import PILFile, TableStoreFiledir
from datapipe.store.database import DBConn
from pathlib import Path

In [2]:
from sqlalchemy import create_engine, inspect, text

engine = create_engine("sqlite+pysqlite3:///db.sqlite")

inspector = inspect(engine)
table_names = inspector.get_table_names()

print(table_names)

['assign_batches_to_files_ec25e1e306_meta', 'cvat_annotation', 'cvat_annotation_meta', 'cvat_images', 'cvat_images_meta', 'cvat_task', 'cvat_task_meta', 'cvat_task_sync_table', 'cvat_task_sync_table_meta', 'fetch_annotations_from_cvat_819c133748_meta', 'image', 'image_batches', 'image_batches_meta', 'image_meta', 'input_images_meta', 'upload_batches_to_cvat_76fbfda051_meta', 'write_image_to_s3_6766ee8ec3_meta']

/tmp/ipykernel_2062463/2406967096.py:3: SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().  Implement an import_dbapi() classmethod directly on class <class 'sqlalchemy_pysqlite3.SQLiteDialect_pysqlite3'> to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.
  engine = create_engine("sqlite+pysqlite3:///db.sqlite")

In [3]:
import pandas as pd

In [4]:
df__image = pd.read_sql_query("SELECT * FROM image", con=engine)

In [5]:
df__image

,image_id,task_queue_id,image__s3_image_path,annotations
0,01,queue1,s3://ainventory-store//datapipe-cvat-test/01.jpeg,"\n <image>\n <polygon label=""pip..."
1,02,queue1,s3://ainventory-store//datapipe-cvat-test/02.jpeg,"\n <image>\n <polygon label=""doc..."
2,03,queue1,s3://ainventory-store//datapipe-cvat-test/03.jpeg,"\n <image>\n <box label=""price_t..."
3,04,queue1,s3://ainventory-store//datapipe-cvat-test/04.jpeg,"\n <image>\n <box label=""cup"" so..."
4,05,queue1,s3://ainventory-store//datapipe-cvat-test/05.jpeg,<image></image>
5,06,queue2,s3://ainventory-store//datapipe-cvat-test/06.jpeg,<image></image>
6,07,queue2,s3://ainventory-store//datapipe-cvat-test/07.jpeg,<image></image>
7,08,queue2,s3://ainventory-store//datapipe-cvat-test/08.jpeg,<image></image>

In [6]:
df__image_batches = pd.read_sql_query("SELECT * FROM image_batches", con=engine)

In [7]:
df__image_batches

  image_id task_queue_id  inner_task_id
0       01        queue1              0
1       02        queue1              0
2       03        queue1              1
3       04        queue1              1
4       07        queue2              0
5       08        queue2              0

In [8]:
df__cvat_task = pd.read_sql_query("SELECT * FROM cvat_task", con=engine)
df__cvat_images = pd.read_sql_query("SELECT * FROM cvat_images", con=engine)
df__cvat_task_sync_table = pd.read_sql_query("SELECT * FROM cvat_task_sync_table", con=engine)
df__cvat_annotation = pd.read_sql_query("SELECT * FROM cvat_annotation", con=engine)

In [9]:
df__cvat_task

   project_id task_queue_id  inner_task_id  task_id
0          24        queue1              0      337
1          24        queue1              1      338
2          24        queue2              0      339

In [10]:
df__cvat_task_sync_table

,project_id,task_queue_id,inner_task_id,task_id,cvat_job__status,cvat_job__last_updated
0,24,queue1,0,337,new,2025-08-12 15:25:37.354873
1,24,queue1,1,338,completed,2025-08-12 15:25:51.471319
2,24,queue2,0,339,new,2025-08-12 15:25:59.223049

In [11]:
df__cvat_images

,image_id,task_queue_id,project_id,inner_task_id,task_id,cvat__file_path,inner_frame_id
0,02,queue1,24,0,337,datapipe-cvat-test/02.jpeg,0
1,01,queue1,24,0,337,datapipe-cvat-test/01.jpeg,1
2,03,queue1,24,1,338,datapipe-cvat-test/03.jpeg,0
3,04,queue1,24,1,338,datapipe-cvat-test/04.jpeg,1
4,07,queue2,24,0,339,datapipe-cvat-test/07.jpeg,0
5,08,queue2,24,0,339,datapipe-cvat-test/08.jpeg,1

In [12]:
df__cvat_task_sync_table

,project_id,task_queue_id,inner_task_id,task_id,cvat_job__status,cvat_job__last_updated
0,24,queue1,0,337,new,2025-08-12 15:25:37.354873
1,24,queue1,1,338,completed,2025-08-12 15:25:51.471319
2,24,queue2,0,339,new,2025-08-12 15:25:59.223049

In [13]:
df__cvat_annotation

  image_id task_queue_id                                        annotations
0       03        queue1  <image width="1024" height="1024">\n    <box l...
1       04        queue1  <image width="1024" height="1024">\n    <box l...